package sexshop;
// Generated 29-jun-2017 17:59:48 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private int cedula;
     private String nombreRazonSocial;
     private String direccion;
     private String ruc;
     private String telefono;
     private String correoElectronico;
     private int idCliente;
     private Set detalleventas = new HashSet(0);

    public Cliente() {
    }

	
    public Cliente(int cedula, int idCliente) {
        this.cedula = cedula;
        this.idCliente = idCliente;
    }
    public Cliente(int cedula, String nombreRazonSocial, String direccion, String ruc, String telefono, String correoElectronico, int idCliente, Set detalleventas) {
       this.cedula = cedula;
       this.nombreRazonSocial = nombreRazonSocial;
       this.direccion = direccion;
       this.ruc = ruc;
       this.telefono = telefono;
       this.correoElectronico = correoElectronico;
       this.idCliente = idCliente;
       this.detalleventas = detalleventas;
    }
   
    public int getCedula() {
        return this.cedula;
    }
    
    public void setCedula(int cedula) {
        this.cedula = cedula;
    }
    public String getNombreRazonSocial() {
        return this.nombreRazonSocial;
    }
    
    public void setNombreRazonSocial(String nombreRazonSocial) {
        this.nombreRazonSocial = nombreRazonSocial;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getRuc() {
        return this.ruc;
    }
    
    public void setRuc(String ruc) {
        this.ruc = ruc;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getCorreoElectronico() {
        return this.correoElectronico;
    }
    
    public void setCorreoElectronico(String correoElectronico) {
        this.correoElectronico = correoElectronico;
    }
    public int getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(int idCliente) {
        this.idCliente = idCliente;
    }
    public Set getDetalleventas() {
        return this.detalleventas;
    }
    
    public void setDetalleventas(Set detalleventas) {
        this.detalleventas = detalleventas;
    }




}


