package sexshop;
// Generated 29-jun-2017 17:59:48 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Detalleventa generated by hbm2java
 */
public class Detalleventa  implements java.io.Serializable {


     private int id;
     private Articulo articulo;
     private Cliente cliente;
     private Funcionario funcionario;
     private Integer cantidad;
     private Float importe;
     private Date fecha;
     private int clienteIdCliente;

    public Detalleventa() {
    }

	
    public Detalleventa(int id, Articulo articulo, Cliente cliente, Funcionario funcionario, int clienteIdCliente) {
        this.id = id;
        this.articulo = articulo;
        this.cliente = cliente;
        this.funcionario = funcionario;
        this.clienteIdCliente = clienteIdCliente;
    }
    public Detalleventa(int id, Articulo articulo, Cliente cliente, Funcionario funcionario, Integer cantidad, Float importe, Date fecha, int clienteIdCliente) {
       this.id = id;
       this.articulo = articulo;
       this.cliente = cliente;
       this.funcionario = funcionario;
       this.cantidad = cantidad;
       this.importe = importe;
       this.fecha = fecha;
       this.clienteIdCliente = clienteIdCliente;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Articulo getArticulo() {
        return this.articulo;
    }
    
    public void setArticulo(Articulo articulo) {
        this.articulo = articulo;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Funcionario getFuncionario() {
        return this.funcionario;
    }
    
    public void setFuncionario(Funcionario funcionario) {
        this.funcionario = funcionario;
    }
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }
    public Float getImporte() {
        return this.importe;
    }
    
    public void setImporte(Float importe) {
        this.importe = importe;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public int getClienteIdCliente() {
        return this.clienteIdCliente;
    }
    
    public void setClienteIdCliente(int clienteIdCliente) {
        this.clienteIdCliente = clienteIdCliente;
    }




}


