package sexshop;
// Generated 07-jul-2017 20:54:18 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Detalledecompra generated by hbm2java
 */
public class Detalledecompra  implements java.io.Serializable {


     private int id;
     private Articulo articulo;
     private Funcionario funcionario;
     private Proveedor proveedor;
     private Integer cantidad;
     private Float importe;
     private Date fecha;

    public Detalledecompra() {
    }

	
    public Detalledecompra(int id, Articulo articulo, Funcionario funcionario, Proveedor proveedor) {
        this.id = id;
        this.articulo = articulo;
        this.funcionario = funcionario;
        this.proveedor = proveedor;
    }
    public Detalledecompra(int id, Articulo articulo, Funcionario funcionario, Proveedor proveedor, Integer cantidad, Float importe, Date fecha) {
       this.id = id;
       this.articulo = articulo;
       this.funcionario = funcionario;
       this.proveedor = proveedor;
       this.cantidad = cantidad;
       this.importe = importe;
       this.fecha = fecha;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Articulo getArticulo() {
        return this.articulo;
    }
    
    public void setArticulo(Articulo articulo) {
        this.articulo = articulo;
    }
    public Funcionario getFuncionario() {
        return this.funcionario;
    }
    
    public void setFuncionario(Funcionario funcionario) {
        this.funcionario = funcionario;
    }
    public Proveedor getProveedor() {
        return this.proveedor;
    }
    
    public void setProveedor(Proveedor proveedor) {
        this.proveedor = proveedor;
    }
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }
    public Float getImporte() {
        return this.importe;
    }
    
    public void setImporte(Float importe) {
        this.importe = importe;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


