package sexshop;
// Generated 07-jul-2017 20:54:18 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Funcionario generated by hbm2java
 */
public class Funcionario  implements java.io.Serializable {


     private String cedula;
     private String nombre;
     private String apellido;
     private String correo;
     private String telefono;
     private Integer cargo;
     private String pass;
     private Set detalleventas = new HashSet(0);
     private Set detalledecompras = new HashSet(0);

    public Funcionario() {
    }

	
    public Funcionario(String cedula) {
        this.cedula = cedula;
    }
    public Funcionario(String cedula, String nombre, String apellido, String correo, String telefono, Integer cargo, String pass, Set detalleventas, Set detalledecompras) {
       this.cedula = cedula;
       this.nombre = nombre;
       this.apellido = apellido;
       this.correo = correo;
       this.telefono = telefono;
       this.cargo = cargo;
       this.pass = pass;
       this.detalleventas = detalleventas;
       this.detalledecompras = detalledecompras;
    }
   
    public String getCedula() {
        return this.cedula;
    }
    
    public void setCedula(String cedula) {
        this.cedula = cedula;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public Integer getCargo() {
        return this.cargo;
    }
    
    public void setCargo(Integer cargo) {
        this.cargo = cargo;
    }
    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }
    public Set getDetalleventas() {
        return this.detalleventas;
    }
    
    public void setDetalleventas(Set detalleventas) {
        this.detalleventas = detalleventas;
    }
    public Set getDetalledecompras() {
        return this.detalledecompras;
    }
    
    public void setDetalledecompras(Set detalledecompras) {
        this.detalledecompras = detalledecompras;
    }




}


