
package gui;

import java.util.ArrayList;
import java.util.Calendar;
import java.util.Iterator;
import java.util.List;
import javax.swing.JOptionPane;
import org.hibernate.Session;
import sexshop.Articulo;
import sexshop.Cliente;
import sexshop.Funcionario;
import sexshop.HibernateUtil;

/**
 *
 * @author ccp
 */
public class menu extends javax.swing.JFrame {
    Session st = HibernateUtil.getSessionFactory().openSession();
    Calendar c1 = Calendar.getInstance();
    static final int CILIMITE = 1000000;
    private Funcionario userActive;
    /**
     * Creates new form menu
     */
    public menu() {
        //Modo admin
        initComponents();
        st.beginTransaction();
        this.setLocationRelativeTo(null);
        updateAll();
        
    }

    public menu(boolean b) {
        //Modo usuario normal
        initComponents();
        this.setLocationRelativeTo(null);
        st.beginTransaction();
        updateAll();
        ModoNormal();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        t_user = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        t_cantidad = new javax.swing.JLabel();
        t_clientes = new javax.swing.JLabel();
        t_fecha = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        t_busqueda = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        actProducto = new javax.swing.JButton();
        regProducto = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        b_eliminarCliente = new javax.swing.JButton();
        b_funcionario = new javax.swing.JButton();
        b_listaFuncionarios = new javax.swing.JButton();
        b_abastecer = new javax.swing.JButton();
        b_listaProveedores = new javax.swing.JButton();
        b_proveedor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(java.awt.SystemColor.inactiveCaptionBorder);

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Menu Principal");

        t_user.setForeground(new java.awt.Color(255, 255, 255));
        t_user.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t_user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user.png"))); // NOI18N

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrar.png"))); // NOI18N
        jButton8.setBorderPainted(false);
        jButton8.setContentAreaFilled(false);
        jButton8.setFocusPainted(false);
        jButton8.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrar_hover.png"))); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(t_user, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(t_user, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cantidad de Productos: ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cantidad de Clientes: ");

        t_cantidad.setForeground(new java.awt.Color(255, 255, 255));

        t_clientes.setForeground(new java.awt.Color(255, 255, 255));

        t_fecha.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        t_fecha.setForeground(new java.awt.Color(255, 255, 255));
        t_fecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fecha.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(t_clientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(t_cantidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(t_clientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(t_fecha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel4.setBackground(java.awt.SystemColor.inactiveCaptionBorder);

        t_busqueda.setBackground(java.awt.SystemColor.inactiveCaptionBorder);
        t_busqueda.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        t_busqueda.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t_busqueda.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 1, true), "Busqueda rapida: ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 10))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(t_busqueda)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(t_busqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscar_normal.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel5.setBackground(java.awt.SystemColor.inactiveCaptionBorder);
        jPanel5.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        actProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/update_normal.png"))); // NOI18N
        actProducto.setBorderPainted(false);
        actProducto.setContentAreaFilled(false);
        actProducto.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/update_hover.png"))); // NOI18N
        actProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actProductoActionPerformed(evt);
            }
        });
        jPanel5.add(actProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 180, 120));

        regProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reg_normal.png"))); // NOI18N
        regProducto.setBorder(null);
        regProducto.setBorderPainted(false);
        regProducto.setContentAreaFilled(false);
        regProducto.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reg_hover.png"))); // NOI18N
        regProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regProductoActionPerformed(evt);
            }
        });
        jPanel5.add(regProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 180, 120));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lista_normal.png"))); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lista_hover.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 180, 120));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/shop_hover.png"))); // NOI18N
        jButton6.setToolTipText("");
        jButton6.setBorder(null);
        jButton6.setBorderPainted(false);
        jButton6.setContentAreaFilled(false);
        jButton6.setFocusPainted(false);
        jButton6.setFocusable(false);
        jButton6.setPreferredSize(new java.awt.Dimension(100, 25));
        jButton6.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/shop_normal.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 120));

        jPanel6.setBackground(java.awt.SystemColor.inactiveCaptionBorder);
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/listaC_normal.png"))); // NOI18N
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/listaC_hover.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 180, 120));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/updateC_normal.png"))); // NOI18N
        jButton5.setBorder(null);
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/updateC_hover.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 180, 120));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/regC_normal.png"))); // NOI18N
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/recC_hover.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 120));

        b_eliminarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eliminar_normal.png"))); // NOI18N
        b_eliminarCliente.setBorderPainted(false);
        b_eliminarCliente.setContentAreaFilled(false);
        b_eliminarCliente.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eliminar_hover.png"))); // NOI18N
        b_eliminarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_eliminarClienteActionPerformed(evt);
            }
        });
        jPanel6.add(b_eliminarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 180, 120));

        b_funcionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/agregarfunc_normal.png"))); // NOI18N
        b_funcionario.setToolTipText("");
        b_funcionario.setBorderPainted(false);
        b_funcionario.setContentAreaFilled(false);
        b_funcionario.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/agregarfunc_hover.png"))); // NOI18N
        b_funcionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_funcionarioActionPerformed(evt);
            }
        });

        b_listaFuncionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/listaFuncionarios_normal.png"))); // NOI18N
        b_listaFuncionarios.setBorderPainted(false);
        b_listaFuncionarios.setContentAreaFilled(false);
        b_listaFuncionarios.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/listaFuncionarios_hover.png"))); // NOI18N
        b_listaFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_listaFuncionariosActionPerformed(evt);
            }
        });

        b_abastecer.setBorderPainted(false);
        b_abastecer.setContentAreaFilled(false);
        b_abastecer.setEnabled(false);

        b_listaProveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/listaProveedores_normal.png"))); // NOI18N
        b_listaProveedores.setBorderPainted(false);
        b_listaProveedores.setContentAreaFilled(false);
        b_listaProveedores.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/listaFuncionarios_hover.png"))); // NOI18N
        b_listaProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_listaProveedoresActionPerformed(evt);
            }
        });

        b_proveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/agregarProveedor_normal.png"))); // NOI18N
        b_proveedor.setBorderPainted(false);
        b_proveedor.setContentAreaFilled(false);
        b_proveedor.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/agregarfunc_hover.png"))); // NOI18N
        b_proveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_proveedorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(b_funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(b_listaFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(b_abastecer, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(125, 125, 125)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(b_listaProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(b_proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(58, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(b_listaFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_abastecer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b_listaProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //Mostrar Informe de Articulos
        List ListaProductos = new ArrayList(); //No usado
        //List<Articulo> lista = (List<Articulo>)st.createQuery("From Articulo").list();
        UpdateArticulo inf = new UpdateArticulo(this, true, true, userActive);
        //inf.LlenarTabla(lista);
        inf.setTitle("Lista de Articulos xd");
        inf.setLocationRelativeTo(this);
        inf.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void regProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regProductoActionPerformed
        //Formulario de registro de productos
        regArticulo form = new regArticulo(this, true);
        form.setLocationRelativeTo(this);
        form.setVisible(true);
        System.out.println(this.userActive.getNombre());
        form.FuncionarioA(this.userActive);
        this.updateAll();
    }//GEN-LAST:event_regProductoActionPerformed

    private void actProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actProductoActionPerformed
        // Actualizar Producto
        UpdateArticulo form = new UpdateArticulo(this, true);
        List<Articulo> lista = (List<Articulo>)st.createQuery("From Articulo").list();
        form.LlenarTabla(lista);
        form.setLocationRelativeTo(this);
        form.setVisible(true);
    }//GEN-LAST:event_actProductoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // No usado xd
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // Busqueda rapida
        //panelBotones.setVisible(false);
        String ID = t_busqueda.getText();
        if(ID.equals("")){
            JOptionPane.showMessageDialog(this, "Ingrese RUC / Nombre / N.Cedula o ID");
            return;
        }
        //st.beginTransaction();
        List<Articulo> lista = (List<Articulo>)st.createQuery("From Articulo").list();
        List<Cliente> listaC = (List<Cliente>)st.createQuery("From Cliente").list();
        
        try{
            //ID o Cedula ingresado
            int id = Integer.parseInt(ID);
            if(id<CILIMITE){
                Articulo pro = (Articulo)st.load(Articulo.class, id
                ); 
                EnviarRes(pro.getIdproducto(), pro.getNombreProducto(),
                            pro.getCantidadDisponible(),pro.getPrecioCompra(),
                            pro.getPrecioVenta(), pro.getCategoria(),
                            pro.getImagenproducto(), pro.getDescripcion());
            }
            else{
                Cliente pro = (Cliente)st.load(Cliente.class, id);
                EnviarResC(pro.getCedula(), pro.getNombreRazonSocial(), pro.getDireccion()
                            , pro.getRuc(), pro.getTelefono(), pro.getCorreoElectronico());
            }
        }
        catch(Exception e){
            //Nombre o RUC ingresado
            //System.out.println("Se ha ingresado un nombre de producto");
            for (Iterator<Articulo> it = lista.iterator(); it.hasNext();) {
                Articulo pro = it.next();
                if(pro.getNombreProducto().equals(ID)){
                    //System.out.println(pro.getIdproducto());
                    EnviarRes(pro.getIdproducto(), pro.getNombreProducto(),
                              pro.getCantidadDisponible(),pro.getPrecioCompra(),
                              pro.getPrecioVenta(), pro.getCategoria(),
                              pro.getImagenproducto(), pro.getDescripcion());
                    return;
                    }
                }
            JOptionPane.showMessageDialog(this, "No encontrado");
        }
        t_busqueda.setRequestFocusEnabled(true);
        //st.close();
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        regCliente REG = new regCliente(this, true);
        REG.setLocationRelativeTo(this);
        REG.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        //Actualizar cliente:
        
        UpdateCliente Up = new UpdateCliente(this, true);
        List<Cliente> lista = (List<Cliente>)st.createQuery("From Cliente").list();
        Up.LlenarTabla(lista);
        Up.setLocationRelativeTo(this);
        Up.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // Lista de clientes
        List<Cliente> lista = (List<Cliente>)st.createQuery("From Cliente").list();
        //System.out.println("1");
        /*for (Iterator<Cliente> it = lista.iterator(); it.hasNext();) {
            Cliente pro = it.next();
            //System.out.println(pro.getProducto());
            ListaClientes.add(pro);
        }*/
        UpdateCliente inf = new UpdateCliente(this, true, true);
        //System.out.println("2");
        inf.LlenarTabla(lista);
        //System.out.println("3");
        inf.setTitle("Lista de Clientes");
        inf.setLocationRelativeTo(this);
        inf.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void b_eliminarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_eliminarClienteActionPerformed
        // Eliminar Cliente
        List<Cliente> lista = (List<Cliente>)st.createQuery("From Cliente").list();
        UpdateCliente inf = new UpdateCliente(this, true, true);
        inf.LlenarTabla(lista);
        inf.setTitle("Lista de Clientes");
        inf.setLocationRelativeTo(this);
        inf.setVisible(true);
    }//GEN-LAST:event_b_eliminarClienteActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // Compra de articulos
        Compra com = new Compra(this, true);
        com.EnviarUser(this.userActive);
        com.setLocationRelativeTo(this);
        com.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void b_funcionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_funcionarioActionPerformed
        // 
       //List<Funcionario> listaF = (List<Funcionario>)st.createQuery("From Funcionario").list();
       regFuncionario regF = new regFuncionario(this, true);
       regF.setLocationRelativeTo(this);
       regF.setVisible(true);
    }//GEN-LAST:event_b_funcionarioActionPerformed

    private void b_listaFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_listaFuncionariosActionPerformed
        // lista de funcionarios
        //List<Funcionario> listaF = (List<Funcionario>)st.createQuery("From Funcionario").list();
        listaFuncionarios inf = new listaFuncionarios(this, true);
        //inf.LlenarTabla(listaF);
        inf.setTitle("Lista de Funcionarios");
        inf.setLocationRelativeTo(this);
        inf.setVisible(true);
    }//GEN-LAST:event_b_listaFuncionariosActionPerformed

    private void b_proveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_proveedorActionPerformed
        // Agregar Proveedor
        AgregarProveedor ag = new AgregarProveedor(this, true);
        ag.setLocationRelativeTo(this);
        ag.setVisible(true);
    }//GEN-LAST:event_b_proveedorActionPerformed

    private void b_listaProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_listaProveedoresActionPerformed
        // Lista de proveedores
        listaProveedores li = new listaProveedores(this, true);
        li.setLocationRelativeTo(this);
        li.setVisible(true);
        
    }//GEN-LAST:event_b_listaProveedoresActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // Cerrar sesion
        Login l = new Login();
        this.dispose();
        l.setLocationRelativeTo(null);
        l.setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actProducto;
    private javax.swing.JButton b_abastecer;
    private javax.swing.JButton b_eliminarCliente;
    private javax.swing.JButton b_funcionario;
    private javax.swing.JButton b_listaFuncionarios;
    private javax.swing.JButton b_listaProveedores;
    private javax.swing.JButton b_proveedor;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JButton regProducto;
    private javax.swing.JTextField t_busqueda;
    private javax.swing.JLabel t_cantidad;
    private javax.swing.JLabel t_clientes;
    private javax.swing.JLabel t_fecha;
    private javax.swing.JLabel t_user;
    // End of variables declaration//GEN-END:variables

    private void EnviarRes(Integer idproducto, String nombreProducto, Integer cantidadDisponible, Float precioCompra, Float precioVenta, String categoria, byte[] imagenproducto, String descripcion) {
        /*Resultados de busqueda rapida por ID o nombre de articulos*/
        resultadosAR RE = new resultadosAR(this, true);
        RE.Vendedor(this.userActive);
        RE.llenar(idproducto, nombreProducto, cantidadDisponible, precioCompra,
                precioVenta, categoria, imagenproducto, descripcion);
        RE.setLocationRelativeTo(this);
        RE.setVisible(true);
    }
    private void updateAll() {
        /*Llamado al inicio del programa*/
        
        System.out.println("updateAll()");
        String dia, mes, annio;
        dia = Integer.toString(c1.get(Calendar.DATE));
        mes = Integer.toString(c1.get(Calendar.MONTH)+1);
        annio = Integer.toString(c1.get(Calendar.YEAR));
        t_fecha.setText(dia+" / "+mes+" / "+annio);
        List ListaProductos = new ArrayList();
        List<Articulo> lista = (List<Articulo>)st.createQuery("From Articulo").list();
        for (Iterator<Articulo> it = lista.iterator(); it.hasNext();) {
            Articulo pro = it.next();
            System.out.println(pro.getNombreProducto());
            ListaProductos.add(pro);
        }
        List ListaClientes = new ArrayList();
        List<Cliente> listaC = (List<Cliente>)st.createQuery("From Cliente").list();
        for (Iterator<Cliente> it = listaC.iterator(); it.hasNext();) {
            Cliente pro = it.next();
            System.out.println(pro.getCedula());
            ListaClientes.add(pro);
        }
        this.t_busqueda.requestFocus();
        t_clientes.setText(Integer.toString(ListaClientes.size()));
        t_cantidad.setText(Integer.toString(ListaProductos.size()));
        return;
    }

    private void EnviarResC(int cedula, String nombreRazonSocial, String direccion, String ruc, String telefono, String correoElectronico) {
        resultadosC RE = new resultadosC();
        RE.llenarC(cedula, nombreRazonSocial, direccion, ruc, telefono, correoElectronico);
        RE.setLocationRelativeTo(this);
        RE.setVisible(true);
    }

    private void ModoNormal() {
        this.b_listaProveedores.setVisible(false);
        this.b_abastecer.setVisible(false);
        this.b_listaFuncionarios.setVisible(false);
        this.b_funcionario.setVisible(false);
        this.b_eliminarCliente.setVisible(false);
        this.b_proveedor.setVisible(false);
    }

    void enviarUser(Funcionario pro) {
        this.userActive = pro;
        this.t_user.setText(pro.getNombre());
    }
}




/*
public void eliminar(){
   int showConfirmDialog = JOptionPane.showConfirmDialog(null, "Eliminación de Registro", "Desea eliminar este registro.", JOptionPane.YES_NO_OPTION);
   if(showConfirmDialog == 1){
       JOptionPane.showMessageDialog(null, "Registro no eliminado.");
   }
   else{
       st.beginTransaction();
       int selectedRow = this.jTable1.getSelectedRow();
       Object valueAt = model.getValueAt(selectedRow, 0);
       int idArt = Integer.parseInt(valueAt.toString());
       Articulo art = (Articulo)st.load(Articulo.class, idArt);
       st.delete(art);
       st.getTransaction().commit();
       JOptionPane.showMessageDialog(null, "Registro eliminado.");
       arranque();
   }

}

public void retornarArticulo(){
    if(this.jTable1.isEnabled()){
        int selectedRow = this.jTable1.getSelectedRow();
        Object valueAt = model.getValueAt(selectedRow, 0);
        int idArt = Integer.parseInt(valueAt.toString());
        Articulo art = (Articulo)st.load(Articulo.class, idArt);
        this.id.setText(String.valueOf(art.getId()));
        this.des.setText(art.getDes());
        this.tipo.setSelectedItem(art.getTipo().getDes());
        this.pco.setText(String.valueOf(art.getPco()));
        this.pve.setText(String.valueOf(art.getPve()));
        this.por.setText(String.valueOf(art.getPor()));
        this.can.setText(String.valueOf(art.getCan()));
        this.editar.setEnabled(true);
        this.eliminar.setEnabled(true);
        this.nuevo.setEnabled(false);
    }    
}

*/