/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import javax.swing.JOptionPane;
import org.hibernate.Session;
import sexshop.Cliente;
import sexshop.HibernateUtil;

/**
 *
 * @author ccp
 */
public class resultadosC extends javax.swing.JFrame {
    Session st = HibernateUtil.getSessionFactory().openSession();
    private UpdateCliente u;
    private int Cedula;

    /**
     * Creates new form resultadosC
     */
    public resultadosC() {
        initComponents();
        st.beginTransaction();
    }

    public resultadosC(UpdateCliente aThis, boolean b) {
        initComponents();
        st.beginTransaction();
        this.u = aThis;
        b_atras.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        res_nombre = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        t_cedula_ruc = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        res_cedula = new javax.swing.JLabel();
        res_direccion = new javax.swing.JLabel();
        res_telefono = new javax.swing.JLabel();
        res_email = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        b_atras = new javax.swing.JButton();

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Resultados");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(153, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(153, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Nombre:");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        res_nombre.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel3.add(res_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 210, 20));

        jLabel4.setText("Direccion:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        jLabel5.setText("Telefono:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        t_cedula_ruc.setText("Cedula:");
        jPanel3.add(t_cedula_ruc, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        jLabel7.setText("Email:");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        res_cedula.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel3.add(res_cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 210, 20));

        res_direccion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel3.add(res_direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 210, 20));

        res_telefono.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel3.add(res_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 210, 20));

        res_email.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel3.add(res_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 210, 20));

        jButton1.setText("Actualizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, -1, -1));

        jButton2.setText("Eliminar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, -1, -1));

        b_atras.setText("Atras");
        b_atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_atrasActionPerformed(evt);
            }
        });
        jPanel3.add(b_atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_atrasActionPerformed
        this.dispose();
        this.u.setVisible(true);
    }//GEN-LAST:event_b_atrasActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Boton Borrar
        // Si es 0 es si, 1 no, 2 cancelar
        int opcion = JOptionPane.showConfirmDialog(this, "Estas seguro?");
        switch(opcion){
            case(0):{
                //Eliminar cliente
                try{
                    int ce = Integer.parseInt(res_cedula.getText());
                    Cliente art = (Cliente)st.load(Cliente.class, ce);
                    st.delete(art);
                    st.getTransaction().commit();
                    this.dispose();
                    JOptionPane.showMessageDialog(null, "Cliente eliminado.");
                }
                catch(Exception e){
                    this.dispose();
                    JOptionPane.showMessageDialog(null, "No se pudo eliminar el registro");
                    e.printStackTrace();
                }
                break;
            }
            case(1):{
                System.out.println("1");
                break;
            }
            case(2):{
                break;
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Boton actualizar
        UpdateCliente up = new UpdateCliente(null,true,this.Cedula);
        this.dispose();
        up.setLocationRelativeTo(null);
        up.b_atras.setVisible(false);
        up.EnviarRes(this.Cedula, res_nombre.getText(), res_direccion.getText(),
                    null, res_telefono.getText(), res_email.getText());
        up.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(resultadosC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(resultadosC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(resultadosC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(resultadosC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new resultadosC().setVisible(true);
            }
        });
    }

    void llenarC(int cedula, String nombreRazonSocial, String direccion, String ruc, String telefono, String correoElectronico) {
        this.Cedula = cedula;
        res_cedula.setText(Integer.toString(cedula));
        res_nombre.setText(nombreRazonSocial);
        res_direccion.setText(direccion);
        res_telefono.setText(telefono);
        res_email.setText(correoElectronico);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_atras;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel res_cedula;
    private javax.swing.JLabel res_direccion;
    private javax.swing.JLabel res_email;
    private javax.swing.JLabel res_nombre;
    private javax.swing.JLabel res_telefono;
    private javax.swing.JLabel t_cedula_ruc;
    // End of variables declaration//GEN-END:variables

}
