package gui;

import javax.swing.JOptionPane;
import org.hibernate.Session;
import sexshop.Articulo;
import sexshop.Funcionario;
import sexshop.HibernateUtil;

/**
 *
 * @author ccp
 */
public class resultadosAR extends javax.swing.JDialog {
    Session st = HibernateUtil.getSessionFactory().openSession();
    private UpdateArticulo u;
    public Integer ID;
    public Funcionario userActive;
    /**
     * Creates new form resultadosAR
     */
    public resultadosAR(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        st.beginTransaction();
        b_atras.setVisible(false);
    }
    public resultadosAR(UpdateArticulo aThis, boolean b) {
        initComponents();
        this.u = aThis;
        st.beginTransaction();
        b_atras.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        res_articulo = new javax.swing.JLabel();
        res_precioV = new javax.swing.JLabel();
        res_precioC = new javax.swing.JLabel();
        res_cantidad = new javax.swing.JLabel();
        res_categoria = new javax.swing.JLabel();
        res_descripcion = new javax.swing.JLabel();
        image = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        b_atras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Resultados");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Categoria:");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, 20));

        jLabel3.setText("Articulo: ");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        jLabel4.setText("Descripcion:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        jLabel5.setText("Cantidad disponible:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        jLabel6.setText("Precio Compra:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        jLabel7.setText("Precio Venta:");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        res_articulo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel3.add(res_articulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 146, 270, 20));

        res_precioV.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        res_precioV.setText(" ");
        jPanel3.add(res_precioV, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 270, 20));

        res_precioC.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        res_precioC.setText(" ");
        jPanel3.add(res_precioC, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 270, 20));

        res_cantidad.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        res_cantidad.setText(" ");
        jPanel3.add(res_cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 270, 20));

        res_categoria.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        res_categoria.setText(" ");
        jPanel3.add(res_categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 270, 20));

        res_descripcion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        res_descripcion.setText(" ");
        res_descripcion.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        res_descripcion.setAutoscrolls(true);
        res_descripcion.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 255), 1, true));
        jPanel3.add(res_descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 270, 60));

        image.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        image.setText("X");
        jPanel3.add(image, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 240, 110));

        jButton1.setText("Vender");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 380, 110, 30));

        jButton2.setText("Eliminar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, 70, 30));

        jButton3.setText("Actualizar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, -1, 30));

        b_atras.setText("Atras");
        b_atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_atrasActionPerformed(evt);
            }
        });
        jPanel3.add(b_atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, -1, 30));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Llamar a una ventana para seleccionar un cliente o registrarlo xd
        Compra comp = new Compra(null, true, this.ID);
        comp.EnviarUser(this.userActive);
        comp.setLocationRelativeTo(this);
        this.dispose();
        comp.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Para eliminar el producto de la db
        // Si es 0 es si, 1 no, 2 cancelar
        int opcion = JOptionPane.showConfirmDialog(this, "Estas seguro?");
        switch(opcion){
            case(0):{
                //Eliminar articulo
                try{
                    Articulo art = (Articulo)st.load(Articulo.class, this.ID);
                    st.delete(art);
                    st.getTransaction().commit();
                    this.dispose();
                    JOptionPane.showMessageDialog(null, "Articulo eliminado.");
                }
                catch(Exception e){
                    this.dispose();
                    JOptionPane.showMessageDialog(null, "No se pudo eliminar el registro");
                    e.printStackTrace();
                }
                break;
            }
            case(1):{
                JOptionPane.showMessageDialog(null, "Articulo no eliminado :)");
                break;
            }
            case(2):{
                break;
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void b_atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_atrasActionPerformed
        // Volver a UpdateArticulo
        /*UpdateArticulo u = new UpdateArticulo(this, true, true);
        u.setLocationRelativeTo(null);
        u.setVisible(true);*/
        this.setVisible(false);
        this.u.setVisible(true);
    }//GEN-LAST:event_b_atrasActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // Actualizar
        UpdateArticulo up = new UpdateArticulo(null,true,this.ID);
        this.dispose();
        up.setLocationRelativeTo(null);
        //up.b_atras.setVisible(false);
        up.EnviarResA(this.ID, res_articulo.getText(), res_cantidad.getText() ,res_categoria.getText(),
                    res_descripcion.getText(), res_precioV.getText(), res_precioC.getText());
        up.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(resultadosAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(resultadosAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(resultadosAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(resultadosAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                resultadosAR dialog = new resultadosAR(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_atras;
    private javax.swing.JLabel image;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel res_articulo;
    private javax.swing.JLabel res_cantidad;
    private javax.swing.JLabel res_categoria;
    private javax.swing.JLabel res_descripcion;
    private javax.swing.JLabel res_precioC;
    private javax.swing.JLabel res_precioV;
    // End of variables declaration//GEN-END:variables
    void llenar(Integer idproducto, String nombreProducto, Integer cantidadDisponible, Float precioCompra, Float precioVenta, String categoria, byte[] imagenproducto, String descripcion) {
        this.ID = idproducto;
        res_articulo.setText(nombreProducto);
        res_cantidad.setText(Integer.toString(cantidadDisponible));
        res_categoria.setText(categoria);
        res_descripcion.setText(descripcion);
        res_precioC.setText(Float.toString(precioCompra));
        res_precioV.setText(Float.toString(precioVenta));
    }

    public void Vendedor(Funcionario userActive) {
        this.userActive = userActive;
    }
}
