/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.event.ActionListener;
import java.util.Iterator;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.hibernate.Session;
import sexshop.Cliente;
import sexshop.HibernateUtil;

/**
 *
 * @author ccp
 */
public class UpdateCliente extends javax.swing.JDialog {
    Session st = HibernateUtil.getSessionFactory().openSession();
    /**
     * Creates new form UpdateCliente
     * @param parent
     * @param modal
     */
    public UpdateCliente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        st.beginTransaction();
        panel_update.setVisible(false);
        this.setSize(550, 460);
    }

    public UpdateCliente(java.awt.Frame parent, boolean modal, boolean b0) {
        super(parent, modal);
        initComponents();
        //st.beginTransaction();
        panel_update.setVisible(false);
        this.titulo_info.setText("Lista de Clientes");
        this.setSize(550, 460);
        System.out.println("4");
        /* Mostrar informacion de articulo */
        for( ActionListener al : b_buscar.getActionListeners() ) {
            b_buscar.removeActionListener( al );
        }
        System.out.println("5");
        b_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_buscarActionPerformed2(evt);
            }
        });
        System.out.println("6");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_busqueda = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        titulo_info = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        t_busqueda = new javax.swing.JTextField();
        b_buscar = new javax.swing.JButton();
        panel_update = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        t_name = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        t_direccion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        t_telefono = new javax.swing.JTextField();
        t_email = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        t_ci = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        panel_busqueda.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));

        titulo_info.setBackground(new java.awt.Color(0, 204, 153));
        titulo_info.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        titulo_info.setForeground(new java.awt.Color(255, 255, 255));
        titulo_info.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo_info.setText("Actualizar Cliente");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(titulo_info, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(120, 120, 120))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(titulo_info, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N.C.I.", "Nombre", "RUC", "Direccion", "Telefono", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabla);
        if (tabla.getColumnModel().getColumnCount() > 0) {
            tabla.getColumnModel().getColumn(0).setMinWidth(50);
            tabla.getColumnModel().getColumn(0).setPreferredWidth(50);
            tabla.getColumnModel().getColumn(4).setPreferredWidth(70);
        }

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        t_busqueda.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Busqueda rapida", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 10))); // NOI18N
        t_busqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_busquedaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(t_busqueda)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(t_busqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        b_buscar.setText("Buscar");
        b_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_buscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_busquedaLayout = new javax.swing.GroupLayout(panel_busqueda);
        panel_busqueda.setLayout(panel_busquedaLayout);
        panel_busquedaLayout.setHorizontalGroup(
            panel_busquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addGroup(panel_busquedaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(b_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_busquedaLayout.setVerticalGroup(
            panel_busquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_busquedaLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b_buscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE))
        );

        getContentPane().add(panel_busqueda);

        panel_update.setBackground(new java.awt.Color(255, 255, 255));

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Nombre:");
        jPanel6.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, 20));

        t_name.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        t_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t_nameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                t_nameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_nameKeyTyped(evt);
            }
        });
        jPanel6.add(t_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 320, 30));

        jLabel5.setText("Direccion:");
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        jLabel3.setText("Telefono:");
        jPanel6.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        t_direccion.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        t_direccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_direccionKeyTyped(evt);
            }
        });
        jPanel6.add(t_direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 320, 30));

        jLabel6.setText("Email:");
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        t_telefono.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel6.add(t_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 320, 30));

        t_email.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        t_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_emailActionPerformed(evt);
            }
        });
        jPanel6.add(t_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 320, 30));

        jLabel1.setText("N.C.I.:");
        jPanel6.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));
        jPanel6.add(t_ci, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 320, 30));

        jPanel7.setBackground(new java.awt.Color(0, 153, 153));

        jLabel9.setBackground(new java.awt.Color(0, 204, 153));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Actualizar Cliente");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(120, 120, 120))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        jButton3.setText("Actualizar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Atras");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_updateLayout = new javax.swing.GroupLayout(panel_update);
        panel_update.setLayout(panel_updateLayout);
        panel_updateLayout.setHorizontalGroup(
            panel_updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_updateLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_updateLayout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panel_updateLayout.setVerticalGroup(
            panel_updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_updateLayout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(5, 5, 5))
        );

        getContentPane().add(panel_update);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void b_buscarActionPerformed2(java.awt.event.ActionEvent evt){
        resultadosC info = new resultadosC(this, true);
        info.setAlwaysOnTop(true);
        info.setLocationRelativeTo(this);
        String ID = t_busqueda.getText();
        if(ID.equals("")){
            JOptionPane.showMessageDialog(this, "Ingrese Cedula");
        }
        //Session st = HibernateUtil.getSessionFactory().openSession();
        //st.beginTransaction();
        List<Cliente> lista = (List<Cliente>)st.createQuery("From Cliente").list();
        
        try{
            int id = Integer.parseInt(ID);
            Cliente pro = (Cliente)st.load(Cliente.class, id
                ); 
                info.llenarC(pro.getCedula(), pro.getNombreRazonSocial()
                        ,pro.getDireccion(), pro.getRuc(),
                        pro.getTelefono(), pro.getCorreoElectronico());
        }
        catch(Exception e){
            //Nombre ingresado
            System.out.println("Se ha ingresado un ruc de Cliente");
            for (Iterator<Cliente> it = lista.iterator(); it.hasNext();) {
                Cliente pro = it.next();
                if(Integer.toString(pro.getCedula()).equals(ID)){
                    System.out.println(pro.getCedula());
                    info.llenarC(pro.getCedula(), pro.getNombreRazonSocial()
                        ,pro.getDireccion(), pro.getRuc(),
                        pro.getTelefono(), pro.getCorreoElectronico());
                    t_busqueda.requestFocus();
                    return;
                    }
                }
            JOptionPane.showMessageDialog(this, "No encontrado");
            return;
        }
        this.setVisible(false);
        info.setVisible(true);
        t_busqueda.requestFocus();
    }
    private void t_busquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_busquedaActionPerformed
        // no usado
    }//GEN-LAST:event_t_busquedaActionPerformed

    private void b_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_buscarActionPerformed
        // Busqueda rapida de actualizacion
        String ID = t_busqueda.getText();
        if(ID.equals("")){
            JOptionPane.showMessageDialog(this, "Ingrese Nombre o ID de producto");
        }
        //Session st = HibernateUtil.getSessionFactory().openSession();
        //st.beginTransaction();
        List<Cliente> lista = (List<Cliente>)st.createQuery("From Cliente").list();

        try{
            int id = Integer.parseInt(ID);
            Cliente pro = (Cliente)st.load(Cliente.class, id
            );
            EnviarRes(pro.getCedula(), pro.getNombreRazonSocial()
                        ,pro.getDireccion(), pro.getRuc(),
                        pro.getTelefono(), pro.getCorreoElectronico());
        }
        catch(Exception e){
            //Nombre ingresado
            System.out.println("Se ha ingresado un nombre de producto");
            for (Iterator<Cliente> it = lista.iterator(); it.hasNext();) {
                Cliente pro = it.next();
                if(Integer.toString(pro.getCedula()).equals(ID)){
                    System.out.println(pro.getCedula());
                    EnviarRes(pro.getCedula(), pro.getNombreRazonSocial()
                        ,pro.getDireccion(), pro.getRuc(),
                        pro.getTelefono(), pro.getCorreoElectronico());
                    t_busqueda.requestFocus();
                    panel_busqueda.setVisible(false);
                    panel_update.setVisible(true);
                    return;
                }
            }
            JOptionPane.showMessageDialog(this, "No encontrado");
            return;
        }
        t_busqueda.requestFocus();
        panel_busqueda.setVisible(false);
        panel_update.setVisible(true);
        //st.close();
    }//GEN-LAST:event_b_buscarActionPerformed

    private void t_nameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_nameKeyPressed
        //Muestra lo ingresado despues de ingresar el siguiente caracter
        //System.out.println(t_producto.getText());
    }//GEN-LAST:event_t_nameKeyPressed

    private void t_nameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_nameKeyReleased
        /*System.out.println(t_producto.getText());
        Session st = HibernateUtil.getSessionFactory().openSession();
        st.beginTransaction();
        List<Articulo> lista = (List<Articulo>)st.createQuery("From Articulo").list();
        for (Iterator<Articulo> it = lista.iterator(); it.hasNext();) {
            Articulo pro = it.next();
            if(pro.getNombreProducto().equals(t_producto.getText())){
                //System.out.println(pro.getProducto());
                t_ya.setVisible(true);
                b_registrar.setText("Actualizar");
                break;
            }
            else{t_ya.setVisible(false);
                b_registrar.setText("Guardar");}
            //System.out.println(pro.getProducto());
        }*/
    }//GEN-LAST:event_t_nameKeyReleased

    private void t_nameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_nameKeyTyped
        // Key typed del nombre del producto

        //if (!t_producto.getText().equals("")) cont++;
    }//GEN-LAST:event_t_nameKeyTyped

    private void t_direccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_direccionKeyTyped
        //if (!t_cantidad.getText().equals("")) cont++;
    }//GEN-LAST:event_t_direccionKeyTyped

    private void t_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_emailActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // Actualizar producto
        String ci, name, dire, ruc, tel, email;
        ci = t_ci.getText();
        name = t_name.getText();
        dire = t_direccion.getText();
        //ruc = t_ruc.getText();
        tel = t_telefono.getText();
        email = t_email.getText();
        System.out.println(ci);
        try{
            //st.beginTransaction();
            int idArt = Integer.parseInt(ci);

            Cliente cli = (Cliente)st.load(Cliente.class, idArt);
            cli.setNombreRazonSocial(name);
            cli.setDireccion(dire);
            //cli.setRuc(ruc);
            cli.setTelefono(tel);
            cli.setCorreoElectronico(email);
            st.update(cli);
            st.getTransaction().commit();
            JOptionPane.showMessageDialog(null, "Registro de cliente actualizado.");
        }
        catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error - Registro no actualizado.");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // Volver al jdialog update info
        t_busqueda.setText("");
        t_busqueda.requestFocus();
        panel_update.setVisible(false);
        panel_busqueda.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UpdateCliente dialog = new UpdateCliente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_buscar;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panel_busqueda;
    private javax.swing.JPanel panel_update;
    private javax.swing.JTextField t_busqueda;
    private javax.swing.JLabel t_ci;
    private javax.swing.JTextField t_direccion;
    private javax.swing.JTextField t_email;
    private javax.swing.JTextField t_name;
    private javax.swing.JTextField t_telefono;
    private javax.swing.JTable tabla;
    private javax.swing.JLabel titulo_info;
    // End of variables declaration//GEN-END:variables

    private void EnviarRes(int cedula, String nombreRazonSocial, String direccion, String ruc, String telefono, String correoElectronico) {
        t_name.setText(nombreRazonSocial);
        t_direccion.setText(direccion);
        t_telefono.setText(telefono);
        t_email.setText(correoElectronico);
        t_ci.setText(Integer.toString(cedula));
        //t_ruc.setText();
    }
    void LlenarTabla(List<Cliente> lista) {
        //DefaultTableModel dtm= new DefaultTableModel();
        DefaultTableModel dtm = (DefaultTableModel) this.tabla.getModel();
        //System.out.println(ListaProductos.size());
        //Object[] data = new Object[5];
        for (Iterator<Cliente> it = lista.iterator(); it.hasNext();) {
            Cliente pro = it.next();
            dtm.addRow(new Object[]{
                            pro.getCedula(), pro.getNombreRazonSocial(),
                            pro.getRuc(), pro.getDireccion(), pro.getTelefono(),
                            pro.getCorreoElectronico()
            });
        }
        tabla.setModel(dtm);
        /*for(int row = 0; row < 2; row++) {
        for(int column = 0; column < 2; column++) {
        data[column] = "Celda " + row + "," + column;
        }
        dtm.addRow(data);
        }*/
        /*for (Iterator it = ListaProductos.iterator(); it.hasNext();) {
            Object ListaProducto = it.next();
            System.out.println(ListaProducto);
        }*/
    }
}

